#!/bin/bash
#
# Hack build script by Halfgaar for building for the BBB Audio Decoder

# TODO: describe how to get the config from the Beagle Bone Black and install it here before compiling

PATH="/home/halfgaar/notbackedup/ti-sdk/ti-processor-sdk-linux-am335x-evm-03.03.00.04/linux-devkit/sysroots/x86_64-arago-linux/usr/bin:$PATH"

make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- && 
scp sound/soc/davinci/snd-soc-davinci-mcasp.ko root@192.168.178.104:/lib/modules/4.4.30-ti-r64/kernel/sound/soc/davinci
